services:
  dokploy:
    image: dokploy/dokploy:v0.27.0
    container_name: dokploy
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    networks:
      - dok-net
    volumes:
      - dokploy-data:/app/data

  postgres:
    image: postgres:16
    container_name: dokploy-postgres
    environment:
      POSTGRES_PASSWORD: dokploy
      POSTGRES_USER: dokploy
      POSTGRES_DB: dokploy
    networks:
      - dok-net
    volumes:
      - dokploy-pg:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: dokploy-redis
    networks:
      - dok-net
    command: ["redis-server", "--appendonly", "yes"]

networks:
  dok-net:

volumes:
  dokploy-data:
  dokploy-pg:
