apiVersion: v1
kind: Namespace
metadata:
  name: glpi
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: glpi
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mariadb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: glpi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.6
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: glpi
            - name: MYSQL_DATABASE
              value: glpidb
            - name: MYSQL_USER
              value: glpi
            - name: MYSQL_PASSWORD
              value: glpi
          volumeMounts:
            - name: mariadb-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mariadb-data
          hostPath:
            path: /data/nginx/mariadb       # <‑‑ même dossier racine que NGINX
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: glpi
  namespace: glpi
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30070
  selector:
    app: glpi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: glpi
  namespace: glpi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glpi
  template:
    metadata:
      labels:
        app: glpi
    spec:
      containers:
        - name: glpi
          image: glpi/glpi:11.0.5
          env:
            - name: GLPI_DB_HOST
              value: mariadb
            - name: GLPI_DB_NAME
              value: glpidb
            - name: GLPI_DB_USER
              value: glpi
            - name: GLPI_DB_PASSWORD
              value: glpi
          volumeMounts:
            - name: glpi-data
              mountPath: /var/glpi       # GLPI servira ce dossier
      volumes:
        - name: glpi-data
          hostPath:
            path: /data/nginx/glpi          # <‑‑ REUTILISATION EXACTE DE TON DOSSIER
            type: DirectoryOrCreate
